Repository HackSC/odyssey, pull requests merged in 2020-12, with the labels that each got.

#469 Andreas/dynamic helpful links
  api/people.js
  components/Navbar.tsx
  express.js
  lib/authenticate.ts
  lib/index.ts
  lib/slack.ts
  package.json
  pages/admin/admin-stats.tsx
  pages/admin/appReview.tsx
  pages/admin/battlepassManager.tsx
  pages/admin/checkin.tsx
  pages/admin/hackerManager.tsx
  pages/admin/helpfulLinkManager.tsx
  pages/admin/houseManager.tsx
  pages/admin/index.tsx
  pages/admin/judgingManager.tsx
  pages/admin/live.tsx
  pages/admin/mailQuery.tsx
  pages/admin/manageApiDirectory.tsx
  pages/admin/roleManager.tsx
  pages/admin/scan.tsx
  pages/admin/scheduleManager.tsx
  pages/admin/taskManager.tsx
  pages/admin/testconsole.tsx
  pages/dashboard.tsx
  pages/houseManager.tsx
  pages/maps.tsx
  pages/projectTeam.tsx
  pages/results.tsx
  pages/sponsor.tsx
  pages/team.tsx
  pages/teams.tsx
  pages/testconsole.tsx
  pages/volunteer.tsx
  yarn.lock
Labels: Live Action, Stability, enhancement, fullstack

#472 Andreas/manage roles
  api/points.js
  api/tasks.js
  api/unlockable.js
  components/Footer.tsx
  components/Navbar.tsx
  components/ToggleSwitch.tsx
  components/index.ts
  cypress/integration/odysseyTests/sponsor_sanity.spec.js
  lib/index.ts
  lib/live.ts
  package.json
  pages/_document.tsx
  pages/admin/admin-stats.tsx
  pages/admin/appReview.tsx
  pages/admin/battlepassManager.tsx
  pages/admin/checkin.tsx
  pages/admin/hackerManager.tsx
  pages/admin/helpfulLinkManager.tsx
  pages/admin/houseManager.tsx
  pages/admin/index.tsx
  pages/admin/mailQuery.tsx
  pages/admin/scan.tsx
  pages/admin/taskManager.tsx
  pages/admin/testconsole.tsx
  pages/sponsor.tsx
  styles/Container.tsx
  yarn.lock
Labels: Live Action, Stability, app review, dependencies, enhancement, epic, fullstack

#477 Fix app review
  api/live.js
  package.json
  pages/admin/appReview.tsx
  pages/admin/scan.tsx
  yarn.lock
Labels: app review, enhancement

#486 fix styling and remove more console.logs
  pages/admin/admin-stats.tsx
  pages/application.tsx
  pages/index.tsx
  tasks/dbSeeder.js
Labels: automerge, bug

#485 Staging
  pages/admin/admin-stats.tsx
  pages/application.tsx
  pages/index.tsx
  tasks/dbSeeder.js
  yarn.lock
Labels: automerge

#488 Andreas/export resumes
  api/hackerProfile.js
  lib/api-sdk/fetcher.ts
  package.json
  pages/_document.tsx
  pages/admin/hackerManager.tsx
  pages/admin/judgingManager.tsx
  yarn.lock
Labels: Stability, app review, enhancement, fullstack

#496 Add basic modal component and allow viewing hackers full profile in Manage Hacker page
  components/Modal.tsx
  components/steps/Status.tsx
  package.json
  pages/admin/hackerManager.tsx
  pages/admin/testconsole.tsx
  yarn.lock
Labels: automerge

#494 Staging
  api/hackerProfile.js
  components/Modal.tsx
  components/steps/Status.tsx
  lib/api-sdk/fetcher.ts
  package.json
  pages/_document.tsx
  pages/admin/hackerManager.tsx
  pages/admin/judgingManager.tsx
  pages/admin/testconsole.tsx
  yarn.lock
Labels: Stability, enhancement, fullstack

#499 date fix in result
  components/steps/Results.tsx
Labels: automerge

#503 better buttons with merge fix
  pages/admin/hackerManager.tsx
Labels: automerge

#506 Improve admin visibility message to not include null firstName/lastName
  pages/admin/hackerManager.tsx
Labels: automerge

#484 Team/Teammate Matching
  api/database/migrations/20201012051044-change_api_description.js
  api/database/migrations/20201216025425-teams-add-matching.js
  api/database/migrations/20201216054449-associate-teammate-requests.js
  api/database/migrations/20201217050248-hackerProfile-team-matching.js
  api/database/migrations/20201224162757-associate-hackerid-teammate-requests.js
  api/hackerProfile.js
  api/models/hackerProfile.js
  api/models/pendingTeammateRequests.js
  api/models/team.js
  api/team.js
  api/teamMatching.js
  assets/linkedin.svg
  components/ButtonWithTextForm.tsx
  components/Team.tsx
  components/TeamSuggestions.tsx
  components/TeammateSuggestions.tsx
  components/steps/Status.tsx
  express.js
  lib/api-sdk/fetcher.ts
  lib/live.ts
  lib/matching.ts
  odyssey.d.ts
  pages/api/hackerProfile.ts
  pages/api/team.ts
  pages/api/teamMatching.ts
  pages/projectTeam.tsx
  pages/team.tsx
  pages/teams.tsx
Labels: enhancement, epic, fullstack, help wanted

#504 Automate ending application submissions 3 days after apps close with new hackathonConstant and small Hackbot update
  components/LiveDashboard.tsx
  components/steps/Status.tsx
  lib/hackathonConstants.ts
  pages/api/slack/appSubmit.ts
  pages/application.tsx
Labels: automerge

#511 Elissa/resume pd fdisplay
  api/hackerProfile.js
  package-lock.json
  package.json
  pages/admin/appReview.tsx
  pages/api/hackerProfile.ts
  public/hack.pdf
  public/pdf.worker.js
  yarn.lock
Labels: automerge

#513 fix app review numbers
  components/Navbar.tsx
  pages/admin/appReview.tsx
Labels: automerge

#514 Andreas/teammatching enhancements
  api/admin.js
  api/teamMatching.js
  components/AdminReview.tsx
  components/Hacker.tsx
  components/Modal.tsx
  components/TeammateSuggestions.tsx
  components/index.ts
  pages/admin/appLeaderboard.tsx
Labels: automerge

#515 Andreas/container exploration - added a simple dockerfile
  Dockerfile
Labels: automerge

#510 Visibility and team matching possibly?
  Dockerfile
  api/admin.js
  api/database/migrations/20201012051044-change_api_description.js
  api/database/migrations/20201216025425-teams-add-matching.js
  api/database/migrations/20201216054449-associate-teammate-requests.js
  api/database/migrations/20201217050248-hackerProfile-team-matching.js
  api/database/migrations/20201224162757-associate-hackerid-teammate-requests.js
  api/hackerProfile.js
  api/models/hackerProfile.js
  api/models/pendingTeammateRequests.js
  api/models/team.js
  api/team.js
  api/teamMatching.js
  assets/linkedin.svg
  components/AdminReview.tsx
  components/ButtonWithTextForm.tsx
  components/Hacker.tsx
  components/LiveDashboard.tsx
  components/Modal.tsx
  components/Navbar.tsx
  components/Team.tsx
  components/TeamSuggestions.tsx
  components/TeammateSuggestions.tsx
  components/index.ts
  components/steps/Status.tsx
  express.js
  lib/api-sdk/fetcher.ts
  lib/hackathonConstants.ts
  lib/live.ts
  lib/matching.ts
  odyssey.d.ts
  package.json
  pages/admin/appLeaderboard.tsx
  pages/admin/appReview.tsx
  pages/admin/hackerManager.tsx
  pages/api/hackerProfile.ts
  pages/api/slack/appSubmit.ts
  pages/api/team.ts
  pages/api/teamMatching.ts
  pages/application.tsx
  pages/projectTeam.tsx
  pages/team.tsx
  pages/teams.tsx
  public/hack.pdf
  public/pdf.worker.js
  yarn.lock
Labels: production

#520 remove superadmin tests - unnecessary right now
  cypress/integration/odysseyTests/superadmin_sanity.spec.js
Labels: automerge, bug

#525 Andreas/hackathon constants manager
  api/database/migrations/20201230161743-hackathon-constants-table.js
  api/hackathonConstants.js
  api/models/hackathonConstants.js
  components/Calendar.tsx
  components/Hacker.tsx
  components/Navbar.tsx
  components/RaffleTicketCount.tsx
  components/steps/CheckedIn.tsx
  express.js
  lib/api-sdk/hook-utils.ts
  lib/authenticate.ts
  lib/hackathonConstants.ts
  lib/index.ts
  lib/judging.ts
  odyssey.d.ts
  pages/admin/admin-stats.tsx
  pages/admin/appLeaderboard.tsx
  pages/admin/appReview.tsx
  pages/admin/battlepassManager.tsx
  pages/admin/checkin.tsx
  pages/admin/hackathonConstantsManager.tsx
  pages/admin/hackerManager.tsx
  pages/admin/helpfulLinkManager.tsx
  pages/admin/houseManager.tsx
  pages/admin/index.tsx
  pages/admin/judgingManager.tsx
  pages/admin/live.tsx
  pages/admin/mailQuery.tsx
  pages/admin/manageApiDirectory.tsx
  pages/admin/passJudgment.tsx
  pages/admin/roleManager.tsx
  pages/admin/scan.tsx
  pages/admin/scheduleManager.tsx
  pages/admin/taskManager.tsx
  pages/admin/testconsole.tsx
  pages/application.tsx
  pages/dashboard.tsx
  pages/index.tsx
  public/pdf.worker.js
  scripts/ticketRaffle.js
  tasks/cli.js
  tasks/dbSeeder.js
  tasks/sendgridsync.js
  tests/api/prize.test.js
Labels: dependencies, enhancement, epic, fullstack

#524 Styling change for App Review, Add superadmins to app leaderboard, migrate hackathon constants to db, create hackathon constants manager on admin dashboard
  api/admin.js
  api/database/migrations/20201230161743-hackathon-constants-table.js
  api/hackathonConstants.js
  api/models/hackathonConstants.js
  components/Calendar.tsx
  components/Hacker.tsx
  components/Navbar.tsx
  components/RaffleTicketCount.tsx
  components/steps/CheckedIn.tsx
  express.js
  lib/api-sdk/hook-utils.ts
  lib/authenticate.ts
  lib/hackathonConstants.ts
  lib/index.ts
  lib/judging.ts
  odyssey.d.ts
  pages/admin/admin-stats.tsx
  pages/admin/appLeaderboard.tsx
  pages/admin/appReview.tsx
  pages/admin/battlepassManager.tsx
  pages/admin/checkin.tsx
  pages/admin/hackathonConstantsManager.tsx
  pages/admin/hackerManager.tsx
  pages/admin/helpfulLinkManager.tsx
  pages/admin/houseManager.tsx
  pages/admin/index.tsx
  pages/admin/judgingManager.tsx
  pages/admin/live.tsx
  pages/admin/mailQuery.tsx
  pages/admin/manageApiDirectory.tsx
  pages/admin/passJudgment.tsx
  pages/admin/roleManager.tsx
  pages/admin/scan.tsx
  pages/admin/scheduleManager.tsx
  pages/admin/taskManager.tsx
  pages/admin/testconsole.tsx
  pages/application.tsx
  pages/dashboard.tsx
  pages/index.tsx
  public/pdf.worker.js
  scripts/ticketRaffle.js
  tasks/cli.js
  tasks/dbSeeder.js
  tasks/sendgridsync.js
  tests/api/prize.test.js
  tsconfig.json
Labels: Live Action, Stability, enhancement, epic, fullstack
