Repository HackSC/odyssey, pull requests merged in 2020-09, with the labels that each got.

#360 staging -> main
  .circleci/config.yml
  components/steps/Status.tsx
  lib/db.ts
  pages/api/admin/review.ts
  pages/api/models/types/index.ts
Labels: app review

#374 Update Live page to show current year
  components/Countdown.tsx
Labels: frontend, invalid

#377 dynamically render date
  pages/admin.tsx
Labels: frontend, invalid

#375 Allow team owners to kick other members
  api/team.js
  components/Team.tsx
Labels: enhancement, fullstack

#373 Andreas/maps page removal
  components/Navbar.tsx
Labels: enhancement, frontend, invalid

#372 fix footer HackSC copyright
  components/Footer.tsx
  components/results/Confirmed.tsx
  components/results/Declined.tsx
  components/steps/Confirmed.tsx
  components/steps/Status.tsx
Labels: bug, frontend, invalid

#362 fix missing application page
  components/steps/Status.tsx
  pages/appform.tsx
Labels: bug

#380 update hacksc header logo
  assets/header_logo_21.png
  assets/header_logo_21_transparent.png
  components/Navbar.tsx
Labels: bug, frontend, invalid

#381 Andreas/cluster schools
  assets/data/majors.json
  assets/data/schools.json
  components/AutocompleteInput.tsx
Labels: enhancement, frontend

#382 Andreas/admin dashboard fix
  api/live.js
  lib/api-sdk/liveHooks.tsx
  pages/admin.tsx
  pages/hackerManager.tsx
Labels: Live Action, enhancement, fullstack
