Repository HackSC/odyssey, pull requests merged in 2021-01, with the labels that each got.

#538 Andreas/dev touch ups
  .github/workflows/release.yml
  README.md
  api/admin.js
  lib/hackathonConstants.ts
  lib/index.ts
  pages/admin/appLeaderboard.tsx
  pages/admin/appReview.tsx
Labels: automerge, enhancement, fullstack, invalid

#540 api route /eligibleReviews only returned if hacker hadnt been review…
  api/admin.js
  pages/admin/appReview.tsx
Labels: Tracking Issue, automerge, bug, production

#553 CheckIn CSS Bugfix
  pages/admin/checkin.tsx
Labels: automerge

#555 fix admin stats and counts
  .gitignore
  api/admin.js
  components/Hacker.tsx
  package.json
  pages/admin/appLeaderboard.tsx
Labels: bug, enhancement

#574 add hackathon constants filtering, logo fix, schedule scroll
  components/hackerDashboard/AdminDashboard.tsx
  components/hackerDashboard/Application.tsx
  components/hackerDashboard/Dashboard.tsx
  components/hackerDashboard/index.ts
  components/hackerDashboard/layout/Header.tsx
  components/hackerDashboard/layout/Navbar.tsx
  components/hackerDashboard/layout/index.ts
  components/hackerDashboard/widgets/admin/index.ts
  components/hackerDashboard/widgets/index.ts
  components/hackerDashboard/widgets/sidebar/events.tsx
  components/hackerDashboard/widgets/updates.tsx
  pages/dashboard.tsx
Labels: frontend
